## **Transformação em NumPy Array**

* Podemos transformar um objeto do tipo DataFrame em um array da biblioteca NumPy.
* Para isto, devemos utilizar o método to_numpy.


In [1]:
import pandas as pd

In [12]:
df = pd.DataFrame({
 'Idade': [20, 21, 25],
 'Altura': [1.75, 1.60, 1.89],
 'Peso': [80, 70, 85]},
  index= ['Andre', 'Bruna', 'Carlos'])

df


Idade  Altura  Peso
Andre      20    1.75    80
Bruna      21    1.60    70
Carlos     25    1.89    85

In [13]:
df.to_numpy()

array([[20.  ,  1.75, 80.  ],
       [21.  ,  1.6 , 70.  ],
       [25.  ,  1.89, 85.  ]])

In [20]:
print(df.loc[:, "Idade"].to_numpy())
print(df.loc[:, "Altura"].to_numpy())
print(df.loc[:, "Peso"].to_numpy())


[20 21 25]
[1.75 1.6  1.89]
[80 70 85]


## **Att**: Podes usar também o to_list()

In [25]:
print(df.loc[:, "Idade"].to_list())
print(df.loc[:, "Altura"].to_list())
print(df.loc[:, "Peso"].to_list())

[20, 21, 25]
[1.75, 1.6, 1.89]
[80, 70, 85]
